### PR TITLE
support basic auth on CHARTMUSEUM type based on helm repository usern…

### PR DESCRIPTION
**Pull request by cr-maayansela**
…ame and password

### CODE REVIEW

**Comment by cr-maayansela** [comment]
https://github.com/kiwigrid/helm-maven-plugin/issues/70

**Comment by jgoeres** [comment]
Any chance that this PR is being merged soon and ends up in a new release? We would need basic auth for CHARTMUSEUM, too. 
THX

**Comment by axdotl** [comment]
Sorry for the late response.
Here we go!

**Comment by axdotl** [comment]
5.2 is on its way.

**Comment by jgoeres** [comment]
Successfully tested basic auth with CHARTMUSEUM using 5.2.  :-)
THX

**Pull request merged**
