### PR TITLE
Auto detect helm executable from PATH by default

### PR DESCRIPTION
**Pull request by masih**
- [x] Add option to auto-detect `helm` from `PATH` if `useLocalHelmBinary` is enabled.
- [x] Fix an issue with OS-specific test; see https://github.com/kiwigrid/helm-maven-plugin/pull/39/commits/aa4dfb526f8020f7b7fbd5ab4cfeb1d5ee331768

See #38

### CODE REVIEW

**Comment by masih** [comment]
@axdotl here is the PR that I _think_ fulfills #38. I decided to separate the flag for auto-detection, because the `helmExecutableDirectory` option is also used as the destination for download.I didn't find a contribution guide in the repo, please let me know if I have missed anything. 
Cheers

**Comment by masih** [comment]
Hi folks, 
I was wondering if you have got a chance to have a look at this. 
Thanks

**Comment by axdotl** [comment]
@rpahli can you've a look on it?

**Comment by masih** [comment]
@rpahli many thanks for the speedy review 🍻

**Pull request merged**
